name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name:  Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build the Docker image Flight
        working-directory: src/FlightServices
        run: docker build . -t jokerva1010123/flight-service:latest
      - name: Build the Docker image Bonus
        working-directory: src/BonusServices
        run: docker build . -t jokerva1010123/bonus-service:latest
      
      - name: Build the Docker image Ticket
        working-directory: src/TicketServices
        run: docker build . -t jokerva1010123/ticket-service:latest
      
      - name: Build the Docker image Gateway
        working-directory: src/Gateway
        run: docker build . -t jokerva1010123/gateway:latest
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the images to Docker Hub
        run: 
          docker push jokerva1010123/flight-service:latest &&
          docker push jokerva1010123/bonus-service:latest &&
          docker push jokerva1010123/ticket-service:latest &&
          docker push jokerva1010123/gateway:latest
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
  
      - name: Check Minikube Cluster
        run: |
          kubectl get pods -A
  
      - name: Create Namespace in Cluster
        run: |
          kubectl create namespace jokerva1010123

      - name: Deploy DB and services
        run: |
          kubectl get namespace
          cd k8s
          echo "------------------Deploy Postgres DB------------------"
          helm delete postgres --namespace jokerva1010123 --ignore-not-found
          helm install -n jokerva1010123 postgres ./postgres_db
          echo "------------------Deploy Services------------------"
          helm delete reserv --namespace jokerva1010123 --ignore-not-found
          helm install -n jokerva1010123 reserv ./services

      - name: Wait 30s
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Get all resources from namespace jokerva1010123 in Cluster
        run: |
          kubectl get all -n jokerva1010123
      - name: Setup Ingress
        run: |
          cd k8s/networking
          minikube service gateway -n jokerva1010123 --url
          kubectl apply -f ingress.yaml
          kubectl get ingress
          sudo echo "$(minikube ip) myapp.local" | sudo tee -a /etc/hosts
          URL=$(minikube service gateway -n jokerva1010123 --url)
          echo "SERVICE_URL=$URL" >> $GITHUB_ENV
          echo "Service URL is: $URL"
          echo "Using service at: ${{ env.SERVICE_URL }}"
      # - name: Setup Postman environment (app url)
      #   uses: sergeysova/jq-action@v2
      #   id: version
      #   with:
      #     cmd: >-
            
      #       jq '.values[0].value = "http://${{ secrets.PROD_HOST }}:${{ secrets.PROD_PORT }}"'
      #       < v1/postman/environment.json > out.tmp &&
      #       mv out.tmp v1/postman/environment.json

      # - uses: education/autograding@v1
      #   id: autograder
      #   continue-on-error: true